### PR TITLE
Input tests marked unstable

### PR DESCRIPTION
**Pull request by felix-capon**

### CODE REVIEW

**Review by hendrikVandeput — COMMENTED** [review]
Why are both tests moved to unstable?

**Comment by felix-capon** [comment]
Both tests seem to be the only ones that fail 
image

**Comment by hendrikVandeput** [comment]
> Both tests seem to be the only ones that fail image

Why are they failing and why should they be allowed to fail?
one of them is a smoke test so I'm expecting the test to be important

**Comment by felix-capon** [comment]
> > Both tests seem to be the only ones that fail image
> 
> Why are they failing and why should they be allowed to fail? one of them is a smoke test so I'm expecting the test to be important

Tests failure reasons are unkown, currently we want the nightly report to work thus surpassing unstable tests.

**Review by hendrikVandeput — DISMISSED** [review]

**Review by hendrikVandeput — APPROVED** [review]

**Pull request merged**
